// While
let contador = 0;
While (contador < 3 )
    Console.log(Contador); 
    Contador++;

    Console.log("Fin del ciclo while"); 

//do while
letconteo = 0;
do{
    console.log(conteo);
    contador++;
}while(conteo< 3);
console.log("Fin del ciclo de white");

//for
for(Let contando = 0; contando < 3; contando++){
    console.log(contando);
}
console.log("fin del ciclo for");

//palabra reservada break
for(let contando =0; < = 10; contando++){
    If (contando % 2 == 0){
        console.log(contando); //muestra todos los pares
        break;
    }
}
console.log("termine el ciclo al encontrar el primer numero par");

//la palabra continue y etiquetas labels
inicio:
for(let contando =0; <= 10; contando++){
    If (contando % 2 !== 0){
        break inicio; //ir a la siguiente interacion
    }
    console.log(contando);
}
console.log("termine el ciclo");










